python -u main.py \
--test \
--sequence_length "$3" \
--prediction_length "$4" \
--delta_rb 30 \
--delta_cog 30 \
--maxVessels 15 \
--param_domain 3.0 \
--eval_batch_size 1 \
--model_type "$1" \
--hidden_size "$2" \
--gpuid 0 \
--dataset_directory dataset/ \
--net_dir models/ \
--criterion "$5" 
